# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='file_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=50)),
                ('upload_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('motto', models.CharField(blank=True, max_length=20)),
                ('talent', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'permissions': (('can_edit_base_profile', 'Can edit base profile'), ('can_view_base_profile', 'Can view base profile'), ('wait', 'Wait')),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('captain_name', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(blank=True, max_length=50)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Interest')),
            ],
            options={
                'permissions': (('can_create_team_profile', 'Can create team profile'), ('can_edit_team_profile', 'Can edit team profile')),
            },
        ),
        migrations.CreateModel(
            name='Teamroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50)),
                ('date_time', models.DateTimeField()),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Student')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Team')),
            ],
        ),
        migrations.CreateModel(
            name='up_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='applier', to='profiles.Team'),
        ),
        migrations.AddField(
            model_name='student',
            name='badge',
            field=models.ManyToManyField(blank=True, to='profiles.Badge'),
        ),
        migrations.AddField(
            model_name='student',
            name='follow',
            field=models.ManyToManyField(blank=True, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Interest'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Role'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Team'),
        ),
        migrations.AddField(
            model_name='file_info',
            name='File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.up_file'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='student1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='student2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='profiles.Student'),
        ),
    ]
