# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_edit_base_profile', 'Can edit base profile'), ('can_view_base_profile', 'Can view base profile'), ('wait', 'Wait'), ('can_insurance', 'Can insurance'), ('can_write_student', 'Can write student'))},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_create_team_profile', 'Can create team profile'), ('can_edit_team_profile', 'Can edit team profile'), ('kicked', 'Kicked'))},
        ),
        migrations.AlterModelOptions(
            name='up_file',
            options={'permissions': (('can_upload', 'Can upload'),)},
        ),
        migrations.AddField(
            model_name='badge',
            name='content',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='insurance',
            name='birthday_d',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insurance',
            name='birthday_m',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insurance',
            name='birthday_y',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='file_info',
            name='upload_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='motto',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.RemoveField(
            model_name='student',
            name='talent',
        ),
        migrations.AlterField(
            model_name='team',
            name='content',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='teamroom',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='domain',
            field=models.ManyToManyField(blank=True, to='profiles.Domain'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='talent',
            field=models.ManyToManyField(blank=True, to='profiles.Talent'),
        ),
    ]
